env:
  browser: true
  jest: true
  node: true
extends:
- "@nuxtjs"
- "plugin:nuxt/recommended"
ignorePatterns:
- "/app/**"
- "/dist/**"
parserOptions:
  parser: "@babel/eslint-parser"
root: true
rules:
  arrow-parens: [error, as-needed]
  camelcase: warn
  comma-dangle: [error, always-multiline]
  curly: warn
  dot-notation: warn
  key-spacing: [error, {align: value}]
  keyword-spacing: warn
  lines-between-class-members: warn
  node/no-callback-literal: "off"
  no-console: "off"
  no-lonely-if: warn
  no-multi-spaces: warn
  no-multiple-empty-lines: warn
  no-return-assign: warn
  no-sequences: warn
  no-throw-literal: "off"
  no-trailing-spaces: warn
  no-undef: warn
  no-unmodified-loop-condition: warn
  no-unused-expressions: warn
  no-var: warn
  nuxt/no-cjs-in-config: warn
  object-curly-newline: warn
  object-shorthand: warn
  prefer-promise-reject-errors: "off"
  quote-props: warn
  require-await: warn
  rest-spread-spacing: warn
  semi: [error, always]
  semi-spacing: warn
  space-before-blocks: warn
  space-before-function-paren:
  - error
  - {anonymous: never, named: never, asyncArrow: always}
  unicorn/prefer-includes: warn
  vue/max-attributes-per-line: warn
  vue/no-v-html: "off"
