env:
  browser: true
  jest: true
  node: true
extends:
- "@nuxtjs"
- "plugin:nuxt/recommended"
ignorePatterns:
- "/app/**"
- "/dist/**"
parserOptions:
  parser: "@babel/eslint-parser"
root: true
rules:
  comma-dangle: [warn, always-multiline]
  node/no-callback-literal: "off"
  no-console: "off"
  no-throw-literal: "off"
  prefer-const: "off"
  prefer-promise-reject-errors: "off"
  quotes: "off"
  semi: [error, always]
  space-before-function-paren:
  - error
  - {anonymous: never, named: never, asyncArrow: always}
  vue/no-v-html: "off"
