linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - importShadow # "forwarder", "tracker", etc. -- to be resolved later.
      - octalLiteral
      - unnamedResult
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  mnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - ^strings\.SplitN$
      - ^os\.FileMode$
      - ^os\.Mkdir(?:All)?$
  lll:
    line-length: 140
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic
    - # Exclude bodyclose when it's passed to client.ProcessRequestForAPI
      # or client.ProcessRequestForUtility which internally closes the body.
      path: src/go/rdctl/
      linters: [ bodyclose ]
      source: "client.ProcessRequestFor(API|Utility)\\(rdClient.DoRequest(WithPayload)?\\("
    - # Exclude ST1005 when it encounters errors starting with proper noun
      linters: [ stylecheck ]
      text: "ST1005:"
      path: src/go/wsl-helper/cmd/kubeconfig.go
      source: errors.New\("Windows
    - # Exclude ST1005 when it encounters errors starting with proper noun
      linters: [ stylecheck ]
      text: "ST1005:"
      path: src/go/rdctl/pkg/lock/lock.go
      source: fmt.Errorf\("Rancher Desktop
    - # Exclude long function declarations
      linters: [ lll ]
      source: ^\s*func\b
    - # Exclude the FIXME comments from upstream
      path: src/go/wsl-helper/pkg/dockerproxy/platform/vsock_linux\.go
      linters: [ gocritic ]
      text: todoCommentWithoutDetail
    - # Ignore errors from syscall
      linters: [ dogsled ]
      source: ^\s*_, _, _ = .*\.Call\(
    - # Ignore foreign constants
      path: src/go/rdctl/pkg/process/process_darwin.go
      linters: [ stylecheck ]
      text: "ST1003:"
      source: ^\s*(CTL_KERN|KERN_PROCARGS)\s*=
    - # Ignore foreign constants
      path: src/go/rdctl/pkg/process/process_windows.go
      linters: [ stylecheck ]
      text: "ST1003:"
      source: ^\s*type\s+[A-Z0-9_]+\s+struct
    - # Ignore foreign constants
      path: src/go/rdctl/pkg/process/process_windows.go
      linters: [ stylecheck ]
      text: "ST1003:"
      source: ^\s*[A-Z0-9_]+\s+=
    - # Don't de-duplicate different commands.
      path: src/go/rdctl/cmd/extension(Install|Uninstall)\.go$
      linters: [ dupl ]
    - # Don't use %q for registry files to avoid escaping backslashes
      path: src/go/rdctl/pkg/reg/reg.go
      linters: [ gocritic ]
      text: "sprintfQuotedString:"
