name: Setup Environment
description: >-
  This is a composite action that is used to set up the runner for running
  Rancher Desktop.

runs:
  using: composite
  steps:
  - name: "Windows: Stop unwanted services"
    if: runner.os == 'Windows'
    shell: pwsh
    run: >-
      Get-Service -ErrorAction Continue -Name
      @('W3SVC', 'docker')
      | Stop-Service

  - name: "Windows: Update any pre-installed WSL"
    if: runner.os == 'Windows'
    shell: pwsh
    run: |
      # Sometimes this results in a HTTP 403 for some reason; in that case, we
      # need to retry.
      do {
        try {
          wsl --update
          break
        } catch [Exception] {
          Write-Host $_.Exception.Message
        }
      } while ($true)

  - name: "Windows: Finish setting up WSL"
    if: runner.os == 'Windows'
    shell: pwsh
    run: wsl --set-default-version 2

  - name: "Linux: Enable KVM access"
    if: runner.os == 'Linux'
    shell: bash
    run: sudo chmod a+rwx /dev/kvm

  - name: "Linux: Initialize pass"
    if: runner.os == 'Linux'
    shell: bash
    run: |
      # Configure the agent to allow default passwords
      HOMEDIR="$(gpgconf --list-dirs homedir)" # spellcheck-ignore-line
      mkdir -p "${HOMEDIR}"
      chmod 0700 "${HOMEDIR}"
      echo "allow-preset-passphrase" >> "${HOMEDIR}/gpg-agent.conf"

      # Create a GPG key
      gpg --quick-generate-key --yes --batch --passphrase '' \
        user@rancher-desktop.test default \
        default never

      # Get info about the newly created key
      DATA="$(gpg --batch --with-colons --with-keygrip --list-secret-keys)"
      FINGERPRINT="$(awk -F: '/^fpr:/ { print $10 ; exit }' <<< "${DATA}")" # spellcheck-ignore-line
      GRIP="$(awk -F: '/^grp:/ { print $10 ; exit }' <<< "${DATA}")"

      # Save the password
      gpg-connect-agent --verbose "PRESET_PASSPHRASE ${GRIP} -1 00" /bye

      # Initialize pass
      pass init "${FINGERPRINT}"
