name: Bug Report
description: Report Rancher Desktop issue
title: "[Bug]- "
labels: "bug :bug:"
body:
- type: input
  attributes:
    label: Rancher Desktop Version
    description: What version of Rancher Desktop are you using?
    placeholder: 0.6.1
  validations:
    required: true
- type: dropdown
  attributes:
    label: What operating system are you using?
    options:
      - macOS
      - Windows
      - Ubuntu
      - Other Linux
      - Other (specify below)
  validations:
    required: true
- type: input
  attributes:
    label: Operating System / Build Version
    description: What operating system and build version are you using?
    placeholder: "e.g. Windows 10 version 1909, macOS Catalina 10.15.7, or Ubuntu 20.04"
  validations:
    required: true
- type: dropdown
  attributes:
    label: What CPU architecture are you using?
    options:
      - x64
      - ia32
      - arm64 (Apple Silicon)
      - Other (specify below)
  validations:
    required: true
- type: textarea
  attributes:
    label: Windows User Only
    description: Are you using VPN, Proxy, Special Firewall rules, Security Software or custom Activity directory features?
    placeholder: "e.g. VPN PulseSecure, Kaspersky Total Security 21.2.x, custom proxy configs or activity directory features..."
  validations:
    required: false
- type: textarea
  attributes:
    label: Actual Behavior
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: Please, describe the steps to reproduce the behaviour.
  validations:
    required: true
- type: textarea
  attributes:
    label: Result
    description: Please, show what error or behaviour you're seeing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: Add any other context about the problem here. Excerpt, attach logs or include screenshots if appropriate.
