# Default Lima configuration; parts will be overridden in code.

ssh:
  loadDotSSHPubKeys: false
firmware:
  legacyBIOS: true
containerd:
  system: false
  user: false
provision:
- # This sets up the K3s persistent volumes.
  # It is run on every boot, not just initial VM provisioning.
  mode: system
  script: |
    #!/bin/sh
    set -o errexit -o nounset -o xtrace
    errors=0
    for dir in /etc/rancher; do
      if [ -d "${dir}" ]; then
        if [ -n "$(ls -A "${dir}")" ]; then
          echo "Directory ${dir} is not empty!" >&2
          errors=1
        fi
      fi
      mkdir -p "/mnt/data/${dir}" "${dir}"
      mount --bind "/mnt/data/${dir}" "${dir}"
    done
    for dir in / /etc/rancher /tmp /var/lib; do
      mount --make-shared "${dir}"
    done
    echo "Done mounting Rancher persistent volumes."
    exit "${errors}"
- # This ensures we have a persisted /etc/machine-id
  mode: system
  script: rc-service machine-id start
