# Default Lima configuration; parts will be overridden in code.

ssh:
  loadDotSSHPubKeys: false
firmware:
  legacyBIOS: true
containerd:
  system: false
  user: false
# Provisioning scripts run on every boot, not just initial VM provisioning.
provision:
- # Clean up filesystems
  mode: system
  script: |
    #!/bin/sh
    set -o errexit -o nounset -o xtrace
    # During boot is the only safe time to delete old k3s versions.
    rm -rf /var/lib/rancher/k3s/data
    # Delete all tmp files older than 3 days.
    find /tmp -depth -mtime +3 -delete
- # Make mount-points shared.
  mode: system
  script: |
    #!/bin/sh
    set -o errexit -o nounset -o xtrace
    for dir in / /etc/rancher /tmp /var/lib; do
      mount --make-shared "${dir}"
    done
- # This sets up cron (used for logrotate)
  mode: system
  script: |
    #!/bin/sh
    # Move logrotate to hourly, because busybox crond only handles time jumps up
    # to one hour; this ensures that if the machine is suspended over long
    # periods, things will still happen often enough.  This is idempotent.
    mv -n /etc/periodic/daily/logrotate /etc/periodic/hourly/
    rc-update add crond default
    rc-service crond start
portForwards:
- guestPortRange: [1, 65535]
  hostIP: "0.0.0.0"
