name: Check for new releases of docker/cli
on:
  schedule:
    - cron: '55 8 * * *'
  workflow_dispatch: {}

permissions:
  issues: write

jobs:
  check-for-token:
    outputs:
      has-token: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW != '' }}
    runs-on: ubuntu-latest
    steps:
    - run: 'true'

  check-docker-cli:
    needs: check-for-token
    if: needs.check-for-token.outputs.has-token == 'true'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: npm ci

      - run: npm run dcmonitor
        env:
          GITHUB_TOKEN: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW }}
