# This workflow downloads artifacts from a (by default, draft) release and runs
# a short smoke test where the application is installed and run and immediately
# shut down.
# Since we need contents-write permissions to look at draft releases, we
# actually download the artifacts in a smaller job, then upload them into the
# run and download it _again_ in the second (per-platform) job where no
# permissions are required.
name: Release smoke test
permissions: {}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: >
          Download artifacts from release with this tag, rather than picking the
          first draft release.
        type: string

jobs:
  download-artifacts:
    name: Find release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to list draft releases
    env:
      RELEASE_TAG: ${{ inputs.tag }}
    steps:
    - name: Find release
      if : inputs.tag == ''
      run: >-
        set -o xtrace;
        printf "RELEASE_TAG=%s\n" >>"$GITHUB_ENV"
        "$(gh api repos/${{ github.repository }}/releases
        --jq 'map(select(.draft))[0].tag_name')"
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Download artifacts
      run: |
        if [[ -z "$RELEASE_TAG" ]]; then
          echo "Failed to find release tag" >&2
          exit 1
        fi
        gh release download "$RELEASE_TAG" \
          --repo ${{ github.repository }} \
          --pattern '*.dmg' \
          --pattern '*.dmg.sha512sum' \
          --pattern '*.msi' \
          --pattern '*.msi.sha512sum' \
          --pattern 'rancher-desktop-linux-*.zip' \
          --pattern 'rancher-desktop-linux-*.zip.sha512sum'
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Upload macOS aarch-64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: application-macos-aarch64.zip
        if-no-files-found: error
        path: |
          *.aarch64.dmg
          *.aarch64.dmg.sha512sum
    - name: Upload macOS x86_64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: application-macos-x86_64.zip
        if-no-files-found: error
        path: |
          *.x86_64.dmg
          *.x86_64.dmg.sha512sum
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: application-win32.zip
        if-no-files-found: error
        path: |
          *.msi
          *.msi.sha512sum
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: application-linux.zip
        if-no-files-found: error
        path: |
          rancher-desktop-linux-*.zip
          rancher-desktop-linux-*.zip.sha512sum

  smoke-test:
    name: Smoke test
    needs: download-artifacts
    strategy:
      fail-fast: false
      matrix:
        include:
        - { platform: macos-aarch64, runs-on: macos-14 }
        - { platform: macos-x86_64, runs-on: macos-13 }
        - { platform: win32, runs-on: windows-latest }
        - { platform: linux, runs-on: ubuntu-latest }
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: "Linux: Enable KVM access"
      if: runner.os == 'Linux'
      run: sudo chmod a+rwx /dev/kvm

    - name: "Linux: Initialize pass"
      if: runner.os == 'Linux'
      run: |
        # Configure the agent to allow default passwords
        HOMEDIR="$(gpgconf --list-dirs homedir)" # spellcheck-ignore-line
        mkdir -p "${HOMEDIR}"
        chmod 0700 "${HOMEDIR}"
        echo "allow-preset-passphrase" >> "${HOMEDIR}/gpg-agent.conf"

        # Create a GPG key
        gpg --quick-generate-key --yes --batch --passphrase '' \
          user@rancher-desktop.test default \
          default never

        # Get info about the newly created key
        DATA="$(gpg --batch --with-colons --with-keygrip --list-secret-keys)"
        FINGERPRINT="$(awk -F: '/^fpr:/ { print $10 ; exit }' <<< "${DATA}")" # spellcheck-ignore-line
        GRIP="$(awk -F: '/^grp:/ { print $10 ; exit }' <<< "${DATA}")"

        # Save the password
        gpg-connect-agent --verbose "PRESET_PASSPHRASE ${GRIP} -1 00" /bye

        # Initialize pass
        pass init "${FINGERPRINT}"

    - name: "Linux: Set startup command"
      if: runner.os == 'Linux'
      run: echo "EXEC_COMMAND=$EXEC_COMMAND" >> "$GITHUB_ENV"
      env:
        EXEC_COMMAND: >-
          exec xvfb-run --auto-servernum
          --server-args='-screen 0 1280x960x24'

    - name: "Windows: Stop unwanted services"
      if: runner.os == 'Windows'
      run: >-
        Get-Service -ErrorAction Continue -Name
        @('W3SVC', 'docker')
        | Stop-Service

    - name: "Windows: Update any pre-installed WSL"
      if: runner.os == 'Windows'
      run: wsl --update
      continue-on-error: true

    - name: "Windows: Set default WSL version"
      if: runner.os == 'Windows'
      run: |
        wsl --set-default-version 2
        wsl --version

    - name: "Windows: Install yq"
      if: runner.os == 'Windows'
      run: |
        set -o xtrace
        bindir="$HOME/bin"
        if [[ ! "$PATH" =~ "$bindir" ]]; then
          bindir=/usr/bin
        fi
        if ! command -v yq; then
          mkdir -p "$bindir"
          curl --location --output "$bindir/yq.exe" \
            https://github.com/mikefarah/yq/releases/latest/download/yq_windows_amd64.exe
          chmod a+x "$bindir/yq.exe"
        fi
      shell: bash

    - name: Set log directory
      shell: bash
      # Use node here to do path manipulation to get correct Windows paths.
      run: >-
        node --eval='console.log("RD_LOGS_DIR=" + require("path").join(process.cwd(), "logs"));'
        >> "$GITHUB_ENV"

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: application-${{ matrix.platform }}.zip
    - run: ${{ env.EXEC_COMMAND }} .github/workflows/smoke-test/smoke-test.sh
      shell: bash
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs-${{ matrix.platform }}.zip
        path: ${{ github.workspace }}/logs
        if-no-files-found: warn
